// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekavtgwcqcwkgfcuxdpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrYXZ0Z3djcWN3a2dmY3V4ZHBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MjMzNTQsImV4cCI6MjA3MTE5OTM1NH0.BtXSoXFeHOk0Ht9--L-7QaM3fXR50UAyQ_eG3COh2TI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});